### ISSUE TITLE
Incompatibility with shrinkwrap and ember-cli-dependency-checker

### ISSUE THREAD

**Issue by wvteijlingen** [drewcovi/ember-cli-stylus#10]
I started using npm shrinkwrap in a project, but unfortunately this doesn't work with ember-cli-dependency-checker. I think this is because ember-cli-stylus specifies `stylus@*`, and broccoli-stylus-single specifies `stylus@0.49.3`. If I use a fork that specifies 0.49.3, all is good.

What would be the best way to deal with this?
- Update the stylus version here to match the one in broccoli-stylus-single?
- Remove the peer dependency from broccoli-stylus-single so that we don't have to include it as a dependency here?

Looking at ember-cli-sass and broccoli-sass-source-maps, it takes the second aproach.

The error:

```
ember-cli-stylus@1.0.5 node_modules/ember-cli-stylus
├── stylus@0.52.4 (css-parse@1.7.0, debug@2.2.0, mkdirp@0.5.1, source-map@0.1.43, sax@0.5.8, glob@3.2.11)
└── broccoli-stylus-single@0.4.1 (include-path-searcher@0.1.0, mkdirp@0.3.5, codependency@0.1.4, rsvp@3.0.21, lodash@2.4.2, stylus@0.49.3, broccoli-caching-writer@0.5.5)

Missing npm-shrinkwrap packages: 
Package: stylus
Required by: my-project / ember-cli-stylus
  * Specified: 0.52.4
  * Installed: 0.49.3
```

**Comment by samtsai** [comment]
I know this issue is quite old but with if we decide to remove `peerDependencies` from this project? I'm also having trouble shrinkwrapping my main project. Mainly due to the mismatch in versions from `ember-cli-stylus` and `broccoli-stylus-single`. I've opened a ticket with that project: https://github.com/gabrielgrant/broccoli-stylus-single/issues/20

That would make the versions match (at least until `stylus` project bumps in versions.

**Comment by drewcovi** [comment]
At the moment I'm pretty buried but always open to a pull request. Feel free to go ahead if you have an idea of how to resolve the issue.

**Comment by samtsai** [comment]
@drewcovi thanks for the response. It looks like this addon doesn't use `peerDependencies` so really I think I have to wait/hope for `broccoli-stylus-single` to publish a new release. I do, however, have some minor updates to documentation in a PR: https://github.com/drewcovi/ember-cli-stylus/pull/22

**Comment by samtsai** [comment]
@drewcovi this is now resolved with the latest 1.0.1 release from https://github.com/gabrielgrant/broccoli-stylus-single/releases/tag/1.0.1

**Comment by samtsai** [comment]
@wvteijlingen @drewcovi this can be closed :)
Better late than never

**Comment by drewcovi** [comment]
:+1:
