### ISSUE TITLE
Super slow compile

### ISSUE THREAD

**Issue by optikalefx** [drewcovi/ember-cli-stylus#16]
This makes me super sad. And really unproductive.

Slowest Trees                                 | Total  
----------------------------------------------+---------------------
StylusCompiler                                | 14068ms             

Slowest Trees (cumulative)                    | Total (avg)  
----------------------------------------------+---------------------
StylusCompiler (1)                            | 14068ms  

It's been in every ember-cli project so far.  My Stylus is fairly large.  For some insight, if I don't include nib, it shaves about 6 seconds off. I don't know what's going on, but it's horrible.

**Comment by sheriffderek** [comment]
How large is your file? kb? mb?

**Comment by optikalefx** [comment]
The final css output is 13.4k.

**Comment by sheriffderek** [comment]
I certainly haven't seen anything this slow, (my files total around 1000 lines or less of stylus) but in general - this is package is "essentially a fork-search-replace job of ember-cli-sass. Credits go to @aexmachina." ~ so I'm curious who involved can help and has the knowhow to improve or re-write this package. I for one, would be very sad if I could not write my styles with stylus in my ember projects / and right now, I can't figure out how to get stylus working with my addons. I don't know the first thing about how this compiler work... so all I could do to help would be to gather some information. Maybe we can look at https://github.com/brunch/stylus-brunch  for inspiration. I'll be thinking of ways to get some eyes on this. We need to have a stable and robust stylus situation for Ember.

**Comment by optikalefx** [comment]
Unfortunately, because this is for work, I had to move on. So I use postCSS now. Which compiles extremely fast. It has an auto-prefixer as well, so I just can't see a reason to spend more time on stylus. :/

**Comment by drewcovi** [comment]
Hey gents, truth is this is only a ember-cli addon extension of broccoli stylus single back when ember addons were new. So any concerns or recommendations for improving compile / performance should be addressed in the broccoli stylus project. Not here.

**Comment by drewcovi** [comment]
To be clear: I have nothing to do with stylus, it's performance, or even really how it's integrated into ember. This project is essentially just a bridge, and time has definitely gotten away from me on keeping it up to speed with the latest cli environment. I'm more than happy to adopt contributors.
