### ISSUE TITLE
Pass plugins to Stylus

### ISSUE THREAD

**Issue by danilovaz** [drewcovi/ember-cli-stylus#17]
Hey guys!

I have an fu *\* ing trouble here :cry: :sob: 

I had a gulpfile.js like this:

``` js
gulp.task('styles', function () {
  gulp.src(paths.cssSource + '**/*.styl')
    .pipe(sourcemaps.init())
    .pipe(stylus({
      use: [
        rupture(),
        poststylus([
          lost(),
          rucksack({ autoprefixer: true })
        ])
      ]
    }))
    .pipe(gcmq())
    .pipe(cssnano())
    .pipe(sourcemaps.write())
    .pipe(gulp.dest(paths.cssDestination))
});
```

But now I have to erase this gulpfile.js and use just ember-cli-build.js (because the framework recommend to use Broccoli to build). So I start to use ember-cli-stylus to compile my styl.

But I'm not able to pass the [Rupture](https://github.com/jescalan/rupture) plugin to the parameter "use" and when I run `ember build` I receive this error:

`rupture has no property .mobile-cutoff`

In the documentation of you, there is nothing very clear about the use of plugins. It would be nice if you had an example in the README.

How can I pass the [Rupture](https://github.com/jescalan/rupture) plugin to Stylus with ember-cli-stylus?

Thank's

**Comment by sheriffderek** [comment]
Any luck on this?

**Comment by drewcovi** [comment]
It appears @danilovaz has released a plugin specifically for rupture. https://github.com/danilovaz/ember-cli-rupture this would be the condoned approach i believe.

**Comment by danilovaz** [comment]
@drewcovi @sheriffderek  Hey :smile: 

Yes, I really try to do this way. But unsuccessfully.

Now, my opinion is: if you will use Ember, so try to use just Broccoli. I know, maybe this isn't the perfect answer. In my project, I remove gulpfile.js and pass my configurations task to ember-cli-build.js and now this works:

``` js
var EmberApp = require('ember-cli/lib/broccoli/ember-app');
var rupture =  require('rupture');
var lost = require('lost');
var rucksack = require('rucksack-css');
var poststylus = require('poststylus');

module.exports = function(defaults) {
  var app = new EmberApp(defaults, {
    stylusOptions: {
      use: [
        rupture(),
        poststylus([
          lost(),
          rucksack({ autoprefixer: true })
        ])
      ]
    }
  return app.toTree();
};

```

**Comment by brancusi** [comment]
@danilovaz that works. Thanks for putting that up!

**Comment by danilovaz** [comment]
@brancusi :beers:
