### ISSUE TITLE
Import 3rd party CSS

### ISSUE THREAD

**Issue by ChiliConSql** [drewcovi/ember-cli-stylus#18]
I am trying to use this library [Picnic](http://picnicss.com/) installed with bower, but can't get it to work.

I've tried this in my styles/app.styl:
`@import '../../bower_components/picnic/picnic.min.css'`

and I tried this:

```
/* ember-cli-build.js */
module.exports = function(defaults) {
  var app = new EmberApp(defaults, {
    // Add options here
    stylusOptions: {
      includePaths: [
        'bower_components/picnic/',
      ],
    }
  });

/* app/styles/app.styl */
@import 'picnic.min.css
```

any suggestions?

**Comment by drewcovi** [comment]
Sorry for the huge delay in response. To be honest I never ran into anything quite like this, but normally I wouldn't even bother including it in app.styl.

This does however sound like something better suited for https://github.com/gabrielgrant/broccoli-stylus-single

**Comment by drewcovi** [comment]
for now closing this as realistically this addon is simply a bridge for broccoli-stylus-single.
