### ISSUE TITLE
Unable to `npm shrinkwrap`

### ISSUE THREAD

**Issue by samtsai** [drewcovi/ember-cli-stylus#2]
Due to a 'peerDepency' on the https://github.com/gabrielgrant/broccoli-stylus-single `npm` can't complete shrinkwrapping. Two cases block us from a successful shrinkwrap.

When you uninstall stylus you'll get this error:
npm ERR! missing: stylus@*, required by broccoli-stylus-single@0.3.0

If you re-install stylus to satisfy the peerDepency, you'll get this:
npm ERR! extraneous: stylus@0.50.0 /Users/tsaisa/Code/awp-ptc/node_modules/ember-cli-stylus/node_modules/stylus

So we either:
- add 'stylus' to your package.json OR
- remove 'stylus' from 'peerDependencies' in the broccoli-stylus-single package.json

**Comment by drewcovi** [comment]
Totally down with either approach. If you throw together a pull request I'll pull it in asap.

**Comment by samtsai** [comment]
Just posted a PR :)

**Comment by samtsai** [comment]
Forgot to update the 'npm' version, could you update that as well for us? Thanks for the quick turnaround!

**Comment by samtsai** [comment]
@drewcovi any chance this can be updated in npm as well? Thanks again and I'll close this once we have the updated package available in npm.

**Comment by drewcovi** [comment]
Totally. I'll have time yet today to tag. Thanks!

**Comment by samtsai** [comment]
@drewcovi could you update the npm package this week? Seeing another issue when the 'stylus' package is not included:
Cannot find module 'mkdirp'
Error: Cannot find module 'mkdirp'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/tsaisa/Code/awp-ptc/node_modules/ember-cli-stylus/node_modules/stylus/lib/middleware.js:15:14)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)

**Comment by drewcovi** [comment]
https://www.npmjs.com/package/ember-cli-stylus v1.0.4

thanks for the patience, ill take another look at this, which version of the cli are you on?

**Comment by samtsai** [comment]
Great!

Opting for cutting edge so I'm on: v0.2.0-beta.1
https://github.com/ember-cli/ember-cli/releases

With this NPM update this should resolve my shrinkwrap issue.

Only other callout is, do you have to update the project package.json to a new version as well? I'm not as familiar with maintaining an npm package - always seems like there's double work ;)

**Comment by drewcovi** [comment]
I believe I did, but let me know if it's not that way for some odd reason. 

＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿
Drew Covi ◍ drewcovi.com ◍ 612.234.2684

**Comment by samtsai** [comment]
I meant the package.json within this project, it still says: '1.0.1'
https://github.com/drewcovi/ember-cli-stylus/blob/master/package.json#L3

**Comment by drewcovi** [comment]
Strange. I definitely committed an update to the tag with the proper version. So many pushes / publishes.

**Comment by drewcovi** [comment]
ah yes, you were on master, i had the tag updated

id update your package.json to just get the latest.

**Comment by drewcovi** [comment]
ive also updated master though

**Comment by samtsai** [comment]
Awesome, thanks for all your help
