### ISSUE TITLE
Importing issues

### ISSUE THREAD

**Issue by omairvaiyani** [drewcovi/ember-cli-stylus#5]
I'm trying to import a css file from`app/style/` like so
`@import 'addons.css'`

This works in production builds, but in development mode, I get an error in console on the browser saying the file was not found. It seems the we need to place additional css files in the public folder for development builds and in the app/style folder for production. Is anyone else experiencing this?

**Comment by drewcovi** [comment]
have you tried `@import addons` ? I'm importing fonts.css that way currently. no issues.

**Comment by drewcovi** [comment]
(no quotes no css)

**Comment by omairvaiyani** [comment]
Hey just tried this, ember-cli gives me this error: `failed to locate @import file addons.styl`

**Comment by drewcovi** [comment]
Hmmmm maybe without the quotes but with the .css? I converted everything I've to styl myself...

**Comment by drewcovi** [comment]
Truth be told though this is probably more a question for broccoli-stylus-single though... I'll see if it's not...

**Comment by omairvaiyani** [comment]
Yeah I think you're right. Anyways, converting to styl fixed the issue! Thanks.
