### ISSUE TITLE
Compiling multiple files

### ISSUE THREAD

**Issue by kara-ryli** [drewcovi/ember-cli-stylus#6]
I'm trying to figure out how to have two CSS files in my application: a mobile-first one, and a desktop one. I've got a config not unlike the Ember CLI guide for [configuring output paths](http://www.ember-cli.com/#configuring-output-paths):

``` javascript
var EmberApp = require("ember-cli/lib/broccoli/ember-app");

var app = new EmberApp({
  outputPaths: {
    app: {
      css: {
        "app": "/assets/app.css",
        'themes/alpha': '/assets/themes/alpha.css'
      }
    }
  }
});
```

And the resulting file structure is:

```
ember-data.js.map
failed.png
passed.png
<app-name>.css
<app-name>.js
<app-name>.map
test-loader.js
test-support.css
test-support.js
test-support.map
vendor.css
vendor.js
vendor.map
```

Is this a bug in ember-cli-stylus, or  a config problem on my side?

**Comment by drewcovi** [comment]
I'm a little booked and out of pocket right now, but you may gain traction over here (which is basically what we're using here with a few ember-cli conventions): 

https://github.com/gabrielgrant/broccoli-stylus-single

**That said,** I've been including multiple stylus files by simply using the @import at the top as discussed in this thread

https://github.com/drewcovi/ember-cli-stylus/issues/5

**Comment by kara-ryli** [comment]
After looking through the code, I think the issue is that this plugin is not looking at outputPaths at all, but just the inputFile field and defaulting to app.styl

Additionally, it doesn't appear that inputFile accepts an array of values. So I think broccoli-stylus-single is working as intended, but that this addon would need to run it for each file in `outputPaths.app.css`.
